[package]
org = "wso2"
name = "project_certificates"
version = "0.1.0"
distribution = "2201.8.5"

[[platform.java17.dependency]]
path="absolute path to your root directory/build/libs/pdf_creator-1.0-SNAPSHOT.jar"
[build-options]
observabilityIncluded = true
